import { NextRequest, NextResponse } from "next/server";
import { coverBufferFromDataUrl } from "@/lib/cover";
import { saveMix } from "@/lib/history";
import { getSpotifySession, SESSION_COOKIE, seal, secureCookieOptions, spotifyUserId } from "@/lib/session";
import { createSpotifyPlaylist, refreshSpotifySession } from "@/lib/spotify";
import type { MixRecord } from "@/lib/types";

export const runtime = "nodejs";

export async function POST(request: NextRequest) {
  try {
    const current = await getSpotifySession();
    if (!current) return NextResponse.json({ error: "Connect Spotify before saving this mix." }, { status: 401 });
    const session = await refreshSpotifySession(current);
    const { mix } = await request.json() as { mix: MixRecord };
    if (!mix?.tracks?.length) return NextResponse.json({ error: "No playlist tracks were provided." }, { status: 400 });
    const userId = spotifyUserId(session);
    if (mix.userId !== userId && mix.userId !== "demo") {
      return NextResponse.json({ error: "This mix belongs to another account." }, { status: 403 });
    }
    await saveMix(userId, { ...mix, userId });
    const playlist = await createSpotifyPlaylist(session, mix.name, `${mix.description} — Generated by Umroo's Music Mixer`, mix.tracks, coverBufferFromDataUrl(mix.coverDataUrl));
    const saved: MixRecord = { ...mix, userId, status: "saved", spotifyId: playlist.id, spotifyUrl: playlist.external_urls.spotify };
    await saveMix(userId, saved).catch((error) => console.warn("Mix history update failed after Spotify save:", error));
    const response = NextResponse.json({ mix: saved });
    if (session.accessToken !== current.accessToken) response.cookies.set(SESSION_COOKIE, seal(session), { ...secureCookieOptions, maxAge: 60 * 60 * 24 * 30 });
    return response;
  } catch (error) {
    console.error(error);
    return NextResponse.json({ error: error instanceof Error ? error.message : "Spotify could not save this playlist." }, { status: 500 });
  }
}
