import sharp from "sharp";
import type { MixPlan } from "@/lib/types";

function xml(value: string) {
  return value.replace(/[<>&'"]/g, (char) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", "'": "&apos;", '"': "&quot;" })[char]!);
}

function hash(value: string) {
  return [...value].reduce((sum, char) => ((sum << 5) - sum + char.charCodeAt(0)) | 0, 0);
}

function palette(value: string) {
  const palettes = [
    ["#182229", "#A34C34", "#E0B68E"], ["#201B2E", "#654B7A", "#E8B89A"],
    ["#142923", "#3E6A55", "#D2A36D"], ["#252019", "#9D6E3C", "#E8D4AF"],
    ["#121821", "#304F72", "#E28A69"], ["#251922", "#7A3E55", "#D7A074"],
  ];
  return palettes[Math.abs(hash(value)) % palettes.length];
}

function wrapTitle(title: string) {
  const words = title.split(/\s+/);
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    if (`${current} ${word}`.trim().length > 18 && current) { lines.push(current); current = word; }
    else current = `${current} ${word}`.trim();
  }
  if (current) lines.push(current);
  return lines.slice(0, 3);
}

function fallbackArtwork(plan: MixPlan) {
  const [dark, mid, light] = palette(`${plan.name}${plan.genres.join("")}`);
  return Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">
    <defs><radialGradient id="g" cx="72%" cy="18%"><stop stop-color="${light}"/><stop offset=".32" stop-color="${mid}"/><stop offset="1" stop-color="${dark}"/></radialGradient><filter id="grain"><feTurbulence baseFrequency=".75" numOctaves="3" seed="4"/><feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 .12 0"/></filter></defs>
    <rect width="1024" height="1024" fill="url(#g)"/><circle cx="760" cy="245" r="115" fill="${light}" opacity=".76"/><path d="M0 730 Q210 510 420 720 T1024 590 V1024 H0Z" fill="${dark}" opacity=".72"/><path d="M0 800 Q270 650 520 790 T1024 700 V1024 H0Z" fill="#0c1115" opacity=".68"/><rect width="1024" height="1024" filter="url(#grain)" opacity=".32"/>
  </svg>`);
}

async function cloudflareArtwork(plan: MixPlan) {
  const account = process.env.CLOUDFLARE_ACCOUNT_ID;
  const token = process.env.CLOUDFLARE_API_TOKEN;
  if (!account || !token) return fallbackArtwork(plan);
  const response = await fetch(`https://api.cloudflare.com/client/v4/accounts/${account}/ai/run/@cf/bytedance/stable-diffusion-xl-lightning`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
      "cf-aig-gateway-id": process.env.CLOUDFLARE_AI_GATEWAY_ID || "default",
    },
    body: JSON.stringify({
      prompt: plan.coverPrompt,
      negative_prompt: "text, letters, words, watermark, logo, portrait, face, clutter",
      width: 1024,
      height: 1024,
      num_steps: 8,
    }),
    signal: AbortSignal.timeout(25_000),
  });
  if (!response.ok) throw new Error(`Cloudflare image generation failed (${response.status})`);
  return Buffer.from(await response.arrayBuffer());
}

export async function createCover(plan: MixPlan) {
  let artwork: Buffer;
  try { artwork = await cloudflareArtwork(plan); } catch (error) {
    console.warn("Using local cover fallback:", error instanceof Error ? error.message : error);
    artwork = fallbackArtwork(plan);
  }
  const lines = wrapTitle(plan.name);
  const startY = 680 - (lines.length - 1) * 66;
  const text = lines.map((line, index) => `<text x="68" y="${startY + index * 90}" fill="#fffaf3" font-family="Arial, Helvetica, sans-serif" font-size="78" font-weight="650" letter-spacing="-2">${xml(line)}</text>`).join("");
  const overlay = Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024">
    <defs><linearGradient id="shade" x1="0" y1="0" x2="0" y2="1"><stop offset=".18" stop-color="#000" stop-opacity=".04"/><stop offset="1" stop-color="#000" stop-opacity=".8"/></linearGradient></defs>
    <rect width="1024" height="1024" fill="url(#shade)"/>${text}
    <text x="72" y="953" fill="#fffaf3" fill-opacity=".76" font-family="Arial, Helvetica, sans-serif" font-size="21" letter-spacing="3">GENERATED BY UMROO'S MUSIC MIXER</text>
  </svg>`);
  let jpeg = await sharp(artwork).resize(1024, 1024, { fit: "cover" }).composite([{ input: overlay }]).jpeg({ quality: 78, mozjpeg: true }).toBuffer();
  if (jpeg.byteLength > 250_000) jpeg = await sharp(jpeg).resize(640, 640).jpeg({ quality: 68, mozjpeg: true }).toBuffer();
  return { jpeg, dataUrl: `data:image/jpeg;base64,${jpeg.toString("base64")}` };
}

export function coverBufferFromDataUrl(value?: string) {
  if (!value?.startsWith("data:image/")) return undefined;
  return Buffer.from(value.split(",")[1] || "", "base64");
}
